services:
  db:
    image: postgres:16
    container_name: bukyt-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bukyt
    ports:
      - "5432:5432"
    volumes:
      - bukyt-db-data:/var/lib/postgresql/data

  web:
    build: .
    container_name: bukyt-web
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./uploads:/app/public/uploads

volumes:
  bukyt-db-data: